manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: dktpham
      url-base: https://github.com/dktpham
  projects:
    - name: infused-kim-zmk
      remote: dktpham
      revision: sofle
      import: app/west.yml
  self:
    path: config
